export enum Permissao {
    ADMIN = 'ROLE_ADMIN',
    ARQUITETO = 'ROLE_ARQUITETO',
    CONSTRUTORA = 'ROLE_CONSTRUTORA',
    //CLIENTE = 'ROLE_CLIENTE',
    DESIGN_INTERIORES = 'ROLE_DESIGN_INTERIORES',
    FORNECEDOR = 'ROLE_FORNECEDOR'
}