export enum TipoFornecedor {
    VIDRACARIA = 'VIDRACARIA',
    MARMORARIA = 'MARMORARIA',
    ESQUADRIA = 'ESQUADRIA',
    AUTOMACAO = 'AUTOMACAO',
    MARCENARIA = 'MARCENARIA',
    MADEREIRA = 'MADEREIRA',
    ELETRICA = 'ELETRICA',
    CLIMATIZACAO = 'CLIMATIZACAO',
    HIDRAULICA = 'HIDRAULICA',
    GESSO = 'GESSO',
    ILUMINACAO = 'ILUMINACAO',
    REVESTIMENTOS = 'REVESTIMENTOS',
    FERRAGEM = 'FERRAGEM',
    OUTROS = 'OUTROS'
}